name: auto-merge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Pull Requests'

jobs:
  auto-merge:
    if: ${{ github.event.workflow-run.conclusion == 'success' }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Merge it
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
          PRESET: DEPENDABOT_MINOR
